#!/usr/bin/env python
import sys
import re

filename = sys.argv[1]

re_startblock = re.compile("^\s*//\s*==UserScript==\s*$")
re_property = re.compile("^\s*//\s*@(\w+)\s*(.*?)\s*$")
re_endblock = re.compile("^\s*//\s*==/UserScript==\s*$")

def re_match_alt(re, target, result_list):
	result_list[:] = [] # empty the list
	result_list.append(re.match(target))
	return result_list[0]

properties = {}
active = False
with open(filename, "r") as fp:
	for line in fp:
		matches = []
		if re_match_alt(re_startblock, line, matches):
			active = True
		elif re_match_alt(re_endblock, line, matches):
			active = False
		elif active and re_match_alt(re_property, line, matches):
			properties.setdefault(matches[0].group(1), []).append(matches[0].group(2))

manifest = {
	'manifest_version': 2,
	'name': properties.get('name', [filename])[0],
	'description': properties.get('description', [''])[0],
	'content_scripts': [{
		'exclude_globs': properties.get('exclude', []),
		'include_globs': properties.get('include', ['*']),
		'js': [filename],
		'matches': properties.get('match', []),
		'run_at': properties.get('run-at', 'document-end').replace('-', '_'),
	}],
	'converted_from_user_script': True,
	'version': properties.get('version', [''])[0],
	'icons': {"128": "logo128.png"},
	'author': "Phillip Bradbury",
	'homepage_url': "http://www.hrwiki.org/wiki/User:Phlip/Greasemonkey",
	'short_name': 'All-In-One',
}
import json
json.dump(manifest, sys.stdout, indent=2)
